# Site wide configuration

title: pitaside
locale: en_US
description: my thought on code and life.
# logo: site-logo.png
search: true
comments: true
url: https://freewayz.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# plugins:
# #   - jekyll-sitemap
# #   - jekyll-gist
#   - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Peter Edache
  avatar: bio-photo-2.jpg
  email: fr33wayz at gmail dot com
  disqus-shortname: freewayz-github-io
  twitter: fr3wayz
  facebook: #username
  github: freewayz
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
